//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ReadMdb
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class plnwatchEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new plnwatchEntities object using the connection string found in the 'plnwatchEntities' section of the application configuration file.
        /// </summary>
        public plnwatchEntities() : base("name=plnwatchEntities", "plnwatchEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new plnwatchEntities object.
        /// </summary>
        public plnwatchEntities(string connectionString) : base(connectionString, "plnwatchEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new plnwatchEntities object.
        /// </summary>
        public plnwatchEntities(EntityConnection connection) : base(connection, "plnwatchEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dil> dil
        {
            get
            {
                if ((_dil == null))
                {
                    _dil = base.CreateObjectSet<dil>("dil");
                }
                return _dil;
            }
        }
        private ObjectSet<dil> _dil;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dil EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodil(dil dil)
        {
            base.AddObject("dil", dil);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="plnwatchModel", Name="dil")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dil : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dil object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static dil Createdil(global::System.Int32 id)
        {
            dil dil = new dil();
            dil.ID = id;
            return dil;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String JENIS_MK
        {
            get
            {
                return _JENIS_MK;
            }
            set
            {
                OnJENIS_MKChanging(value);
                ReportPropertyChanging("JENIS_MK");
                _JENIS_MK = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("JENIS_MK");
                OnJENIS_MKChanged();
            }
        }
        private global::System.String _JENIS_MK;
        partial void OnJENIS_MKChanging(global::System.String value);
        partial void OnJENIS_MKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDPEL
        {
            get
            {
                return _IDPEL;
            }
            set
            {
                OnIDPELChanging(value);
                ReportPropertyChanging("IDPEL");
                _IDPEL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDPEL");
                OnIDPELChanged();
            }
        }
        private Nullable<global::System.Int32> _IDPEL;
        partial void OnIDPELChanging(Nullable<global::System.Int32> value);
        partial void OnIDPELChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAMA
        {
            get
            {
                return _NAMA;
            }
            set
            {
                OnNAMAChanging(value);
                ReportPropertyChanging("NAMA");
                _NAMA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAMA");
                OnNAMAChanged();
            }
        }
        private global::System.String _NAMA;
        partial void OnNAMAChanging(global::System.String value);
        partial void OnNAMAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TARIF
        {
            get
            {
                return _TARIF;
            }
            set
            {
                OnTARIFChanging(value);
                ReportPropertyChanging("TARIF");
                _TARIF = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TARIF");
                OnTARIFChanged();
            }
        }
        private global::System.String _TARIF;
        partial void OnTARIFChanging(global::System.String value);
        partial void OnTARIFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DAYA
        {
            get
            {
                return _DAYA;
            }
            set
            {
                OnDAYAChanging(value);
                ReportPropertyChanging("DAYA");
                _DAYA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DAYA");
                OnDAYAChanged();
            }
        }
        private Nullable<global::System.Int32> _DAYA;
        partial void OnDAYAChanging(Nullable<global::System.Int32> value);
        partial void OnDAYAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LINGKUNGAN
        {
            get
            {
                return _LINGKUNGAN;
            }
            set
            {
                OnLINGKUNGANChanging(value);
                ReportPropertyChanging("LINGKUNGAN");
                _LINGKUNGAN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LINGKUNGAN");
                OnLINGKUNGANChanged();
            }
        }
        private global::System.String _LINGKUNGAN;
        partial void OnLINGKUNGANChanging(global::System.String value);
        partial void OnLINGKUNGANChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TGLPASANG
        {
            get
            {
                return _TGLPASANG;
            }
            set
            {
                OnTGLPASANGChanging(value);
                ReportPropertyChanging("TGLPASANG");
                _TGLPASANG = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TGLPASANG");
                OnTGLPASANGChanged();
            }
        }
        private Nullable<global::System.DateTime> _TGLPASANG;
        partial void OnTGLPASANGChanging(Nullable<global::System.DateTime> value);
        partial void OnTGLPASANGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MEREK_KWH
        {
            get
            {
                return _MEREK_KWH;
            }
            set
            {
                OnMEREK_KWHChanging(value);
                ReportPropertyChanging("MEREK_KWH");
                _MEREK_KWH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MEREK_KWH");
                OnMEREK_KWHChanged();
            }
        }
        private global::System.String _MEREK_KWH;
        partial void OnMEREK_KWHChanging(global::System.String value);
        partial void OnMEREK_KWHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KDGARDU
        {
            get
            {
                return _KDGARDU;
            }
            set
            {
                OnKDGARDUChanging(value);
                ReportPropertyChanging("KDGARDU");
                _KDGARDU = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KDGARDU");
                OnKDGARDUChanged();
            }
        }
        private global::System.String _KDGARDU;
        partial void OnKDGARDUChanging(global::System.String value);
        partial void OnKDGARDUChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NOTIANG
        {
            get
            {
                return _NOTIANG;
            }
            set
            {
                OnNOTIANGChanging(value);
                ReportPropertyChanging("NOTIANG");
                _NOTIANG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NOTIANG");
                OnNOTIANGChanged();
            }
        }
        private global::System.String _NOTIANG;
        partial void OnNOTIANGChanging(global::System.String value);
        partial void OnNOTIANGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KODEAREA
        {
            get
            {
                return _KODEAREA;
            }
            set
            {
                OnKODEAREAChanging(value);
                ReportPropertyChanging("KODEAREA");
                _KODEAREA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KODEAREA");
                OnKODEAREAChanged();
            }
        }
        private global::System.String _KODEAREA;
        partial void OnKODEAREAChanging(global::System.String value);
        partial void OnKODEAREAChanged();

        #endregion
    
    }

    #endregion
    
}
